easy_admin:
    entities:
        # List the entity class name you want to manage
        LandingSlider:
                    class: App\Entity\LandingSlider
                    label: 'Landing Slider'
                    list:
                        title: "Landing Slider"
                        fields:
                          - { property: 'id' }
                          - { property: 'title' }
                          - { property: 'text' }
                          - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    show:
                        fields:
                            - { property: 'id' }
                            - { property: 'title' }
                            - { property: 'text' }
                            - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    form:
                        fields:
                            - { property: 'title' }
                            - { property: 'text' }
                            - { property: 'imageFile', type: 'vich_image' }
        LandingBottom:
                    class: App\Entity\LandingBottom
                    label: 'Landing Bottom'
                    list:
                        title: "Landing Bottom"
                        fields:
                          - { property: 'id' }
                          - { property: 'title' }
                          - { property: 'link' }
                          - { property: 'linkType' }
                          - { property: 'position' }
                          - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                          - { property: 'date_created' }
                    show:
                        fields:
                            - { property: 'id' }
                            - { property: 'title' }
                            - { property: 'link' }
                            - { property: 'linkType' }
                            - { property: 'position' }
                            - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                            - { property: 'date_created' }
                    form:
                        fields:
                            - { property: 'title' }
                            - { property: 'link' }
                            - { property: 'linkType', type: 'choice', type_options: {choices: {'inner':'inner', 'outter':'outter', 'video':'video'}}}
                            - { property: 'position', type: 'choice', type_options: {choices: {'horizontal':'horizontal', 'vertical':'vertical'}}}
                            - { property: 'imageFile', type: 'vich_image' }
                            - { property: 'date_created' }
        News:
            class: App\Entity\News
            label: 'News'
            list:
                title: "Most recent news"
                fields:
                  - { property: 'id' }
                  - { property: 'title' }
                  - { property: 'text' }
                  - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                  - { property: 'date_created' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    - { property: 'date_created' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'date_created' }
        NewsImages:
                    class: App\Entity\NewsImages
                    label: 'News Images'
                    list:
                        title: "Images from news"
                        fields:
                          - { property: 'id' }
                          - { property: 'news' }
                          - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    show:
                        fields:
                            - { property: 'id' }
                            - { property: 'news' }
                            - { property: 'image', type: 'image', base_path: '%app.path.images%' }
                    form:
                        fields:
                            - { property: 'news' }
                            - { property: 'imageFile', type: 'vich_image' }
        NewsPanel:
                    class: App\Entity\NewsPanel
                    label: 'News Panels'
                    list:
                        title: "Texts from news"
                        fields:
                          - { property: 'id' }
                          - { property: 'news' }
                          - { property: 'title' }
                          - { property: 'text' }
                    show:
                        fields:
                            - { property: 'id' }
                            - { property: 'news' }
                            - { property: 'title' }
                            - { property: 'text' }
                    form:
                        fields:
                            - { property: 'news' }
                            - { property: 'title' }
                            - { property: 'text' }