vich_uploader:
    db_driver: orm
    mappings:
        images:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:         '%app.path.images%'
            #upload_destination: '%kernel.root_dir%/../web%app.path.images%'
            upload_destination: '%app.path.images%'