version: 2
jobs:
  deploy-staging:
    docker:
      - image: circleci/php:7.2-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: atp-front
          command: ssh -o "StrictHostKeyChecking no" ${SSH_STAGING_HOST} "cd /var/www/html/atp && git checkout dev-back -f && git pull"