version: 2
jobs:
  deploy-staging:
    docker:
      - image: circleci/php:7.2.8-apache-stretch-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: atp-front
          command: ssh -o "StrictHostKeyChecking no" ${SSH_STAGING_HOST} "cd /var/www/html/atp && git checkout dev-back -f && git pull"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only:
                - dev
                - master
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - deploy-staging
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - hold