version: 2
jobs:
  deploy-staging:
    docker:
      - image: circleci/php:7.2.8-apache-stretch-node-browsers
    steps:
      - add_ssh_keys
      - deploy:
          name: atp-stg
          command: ssh -o "StrictHostKeyChecking no" ${SSH_STAGING_USER_HOST} "cd /var/www/html/atp && git checkout dev-back -f && git pull && chmod a+x ./.circleci/provision.sh && ./.circleci/provision.sh"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only:
                - develop
                - master
                - dev-back
