index:
    path: /
    controller: App\Controller\IndexController::index
backyard:
    path: /backyard
    controller: App\Controller\IndexController::backyardNurseries
community:
    path: /community
    controller: App\Controller\IndexController::community
fruit:
    path: /fruit
    controller: App\Controller\IndexController::fruitHarvesting
news:
    path: /news
    controller: App\Controller\IndexController::news
single:
    path: /single
    controller: App\Controller\IndexController::singleNews
impact:
    path: /impact
    controller: App\Controller\IndexController::impact
economic:
    path: /economic
    controller: App\Controller\IndexController::economic
tree:
    path: /tree
    controller: App\Controller\IndexController::tree
forestation:
    path: /forestation
    controller: App\Controller\IndexController::forestation
donation:
    path: /donation
    controller: App\Controller\IndexController::donation
donationReview:
    path: /donationReview
    controller: App\Controller\IndexController::donationReview
events:
    path: /events
    controller: App\Controller\IndexController::events
logout:
    path: /logout
onetime:
     path: /onetime
     controller: App\Controller\PaypalController::onetime
execute:
     path: /execute
     controller: App\Controller\PaypalController::execute
plan:
     path: /plan
     controller: App\Controller\PaypalController::plan
agreement:
     path: /agreement
     controller: App\Controller\PaypalController::agreement