index:
    path: /
    controller: App\Controller\IndexController::index
backyard:
    path: /backyard
    controller: App\Controller\IndexController::backyardNurseries
community:
    path: /community
    controller: App\Controller\IndexController::community
fruit:
    path: /fruit
    controller: App\Controller\IndexController::fruitHarvesting
news:
    path: /news
    controller: App\Controller\IndexController::news
single:
    path: /single
    controller: App\Controller\IndexController::singleNews
impact:
    path: /impact
    controller: App\Controller\IndexController::impact
economic:
    path: /economic
    controller: App\Controller\IndexController::economic
tree:
    path: /tree
    controller: App\Controller\IndexController::tree
forestation:
    path: /forestation
    controller: App\Controller\IndexController::forestation
donation:
    path: /donation
    controller: App\Controller\IndexController::donation
simpleDonation:
    path: /simpleDonation/{amount}
    controller: App\Controller\IndexController::simpleDonation
    defaults:
            amount: 1000
events:
    path: /events
    controller: App\Controller\IndexController::events
where:
    path: /where
    controller: App\Controller\IndexController::where
education:
    path: /education
    controller: App\Controller\IndexController::education
kids:
    path: /kids
    controller: App\Controller\IndexController::kids
ohanian:
    path: /ohanian
    controller: App\Controller\IndexController::ohanian
ambassador:
    path: /ambassador
    controller: App\Controller\IndexController::ambassador
volunteer:
    path: /volunteer
    controller: App\Controller\IndexController::volunteer
empowering:
    path: /empowering
    controller: App\Controller\IndexController::empowering
mission:
    path: /mission
    controller: App\Controller\IndexController::mission
team:
    path: /team
    controller: App\Controller\IndexController::team
tour:
    path: /tour
    controller: App\Controller\IndexController::tour
bndonate:
    path: /bndonate
    controller: App\Controller\IndexController::bndonate
payment:
    path: /payment/{id}
    controller: App\Controller\IndexController::payment
    defaults:
            id: 1
donateReview:
    path: /donateReview/{id}
    controller: App\Controller\IndexController::donationReview
    defaults:
            id: 1
certificate:
    path: /donation-certificate/{id}
    controller: App\Controller\IndexController::certificate
    defaults:
            id: 1
stewardship:
    path: /stewardship
    controller: App\Controller\IndexController::stewardship
village:
    path: /village
    controller: App\Controller\IndexController::village
enveducation:
    path: /environmental-education
    controller: App\Controller\IndexController::enveducation
mirak:
    path: /mirak
    controller: App\Controller\IndexController::mirak
camps:
    path: /camps
    controller: App\Controller\IndexController::camps
logout:
    path: /logout
onetime:
     path: /onetime
     controller: App\Controller\PaypalCheckoutController::onetime
execute:
     path: /execute
     controller: App\Controller\PaypalCheckoutController::execute
plan:
     path: /plan
     controller: App\Controller\PaypalCheckoutController::plan
agreement:
     path: /agreement
     controller: App\Controller\PaypalCheckoutController::agreement
error:
     path: /error
     controller: App\Controller\PaypalCheckoutController::error
done:
     path: /done
     controller: App\Controller\PaypalCheckoutController::done
interactive:
    path: /interactive
    controller: App\Controller\InteractiveController::interactive
ecogames:
    path: /ecogames
    controller: App\Controller\InteractiveController::ecogames
bbmagazine:
    path: /bbmagazine
    controller: App\Controller\InteractiveController::bbmagazine
videos:
    path: /videos
    controller: App\Controller\InteractiveController::videos
tchalo:
    path: /tchalo
    controller: App\Controller\InteractiveController::tchalo
coloring:
    path: /coloring
    controller: App\Controller\InteractiveController::coloring
treevia:
    path: /treevia
    controller: App\Controller\InteractiveController::treevia
singlepayflow:
     path: /singlepayflow/{id}
     controller: App\Controller\PaypalPayFlowController::onetime
     defaults:
             id: 1
donepayflow:
     path: /donepayflow/{id}
     controller: App\Controller\PaypalPayFlowController::done
     defaults:
              id: 1
errorpayflow:
     path: /errorpayflow/{code}
     controller: App\Controller\PaypalPayFlowController::error
     defaults:
              code: 1
language:
    path: /language/{lang}
    controller: App\Controller\IndexController::language
    defaults:
            lang: Eng
test:
    path: /test
    controller: App\Controller\IndexController::test