index:
    path: /
    controller: App\Controller\IndexController::index
backyard:
    path: /backyard
    controller: App\Controller\IndexController::backyardNurseries
community:
    path: /community
    controller: App\Controller\IndexController::community
fruit:
    path: /fruit
    controller: App\Controller\IndexController::fruitHarvesting
news:
    path: /news
    controller: App\Controller\IndexController::news
single:
    path: /single
    controller: App\Controller\IndexController::singleNews
impact:
    path: /impact
    controller: App\Controller\IndexController::impact
economic:
    path: /economic
    controller: App\Controller\IndexController::economic
tree:
    path: /tree
    controller: App\Controller\IndexController::tree
forestation:
    path: /forestation
    controller: App\Controller\IndexController::forestation
donation:
    path: /donation
    controller: App\Controller\IndexController::donation
events:
    path: /events
    controller: App\Controller\IndexController::events
where:
    path: /where
    controller: App\Controller\IndexController::where
education:
    path: /education
    controller: App\Controller\IndexController::education
kids:
    path: /kids
    controller: App\Controller\IndexController::kids
ohanian:
    path: /ohanian
    controller: App\Controller\IndexController::ohanian
ambassador:
    path: /ambassador
    controller: App\Controller\IndexController::ambassador
volunteer:
    path: /volunteer
    controller: App\Controller\IndexController::volunteer
empowering:
    path: /empowering
    controller: App\Controller\IndexController::empowering
mission:
    path: /mission
    controller: App\Controller\IndexController::mission
team:
    path: /team
    controller: App\Controller\IndexController::team
logout:
    path: /logout
onetime:
     path: /onetime
     controller: App\Controller\PaypalController::onetime
execute:
     path: /execute
     controller: App\Controller\PaypalController::execute
plan:
     path: /plan
     controller: App\Controller\PaypalController::plan
agreement:
     path: /agreement
     controller: App\Controller\PaypalController::agreement
error:
     path: /error
     controller: App\Controller\PaypalController::error
done:
     path: /done
     controller: App\Controller\PaypalController::done
interactive:
    path: /interactive
    controller: App\Controller\InteractiveController::interactive
ecogames:
    path: /ecogames
    controller: App\Controller\InteractiveController::ecogames
bbmagazine:
    path: /bbmagazine
    controller: App\Controller\InteractiveController::bbmagazine
videos:
    path: /videos
    controller: App\Controller\InteractiveController::videos
tchalo:
    path: /tchalo
    controller: App\Controller\InteractiveController::tchalo
coloring:
    path: /coloring
    controller: App\Controller\InteractiveController::coloring
treevia:
    path: /treevia
    controller: App\Controller\InteractiveController::treevia
test:
     path: /test
     controller: App\Controller\PaypalController::test